version: '3.7'

x-base: &base
  build:
    context: .
    dockerfile: Dockerfile
  image: docker-ffmpeg
  init: true
  volumes:
    - ./share:/root/share

services:
  sh:
    <<: *base
    command:
      - bash
    tty: true
